### ISSUE TITLE
Live value of System variables.

### ISSUE THREAD

**Issue by Leander31** [PegasusPool/pegasus-tool-features#17]
Hello people can you consider show up the live value of variables running in the system.
Variables like rho, and tau.
 
My best regards for that team.
Cheers

**Comment by PegasusPool** [comment]
Hi there,

Thank you for your suggestion. It is really appreciated.
I have considered adding this to the app, however the reality is that these parameters would mean nothing for 99% of the users. 
It is essential to keep the application simple and straightforward and I shouldn't put everything in there just because I can.
In reality whoever is aware of these parameters and the meanings of it are very likely have their own way to get this out of the chain.
