### ISSUE TITLE
Epoch Notification 

### ISSUE THREAD

**Issue by AnDresBioEng** [PegasusPool/pegasus-tool-features#21]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

I believe a notification feature for how long the epoch has left and the blocks your favourite pools have mined at that time would be helpful. Having notification for every block is nice, but I like the Idea of getting a status update once the current epoch is 75% done. This tied in with an expected blocks feature will help one gauge whether they should continue to stay with a pool or move. Also a note on the randomness of the protocol will help 
Above the expected blocks could remind stakers that unlucky epochs happen. The apps is great and can’t wait to see how it progresses.

**Comment by PegasusPool** [comment]
Thanks for the suggestion.

Pools will be inevitably unlucky sometimes and may be only assigned 75% or less of the blocks they are "expected" to create according to their live stake. If they create 100% of these blocks in an unlucky epoch it is not right to alert the delegators that the pool only created 75% of the expected blocks and therefore convince them to redelegate their stake from an otherwise very well performing pool.
