### ISSUE TITLE
Lifetime blocks on website ‘pool tool.ico’ and total blocks of PoolTool apr are different each other.

### ISSUE THREAD

**Issue by siwas426** [PegasusPool/pegasus-tool-features#25]
**Describe the bug**
Lifetime blocks on website ‘pooltool.io’ and total blocks of PoolTool apl are different.
Total blocks of PoolTool apl is wrong.

**To Reproduce**
1. Search pool I’d ‘YYG’ on PoolTool apl and on Web site PoolTool.io by pc
2. Compare number of total block of pooltool apl and of WEb site of PoolTool.io. You can see different number. Total blocks of PoolTool apl is wrong

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac OS
 - Browser [e.g. chrome, safari] chrome

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] iphone12
 - OS: [e.g. iOS8.1] iOS 14.3
 - Browser  PoolTool apl

**Comment by PegasusPool** [comment]
Thank you for reporting this issue.
After investigation I found that the issue is the underlying cardano-wallet software that sometimes fail to update the total blocks count for pools. After I restarted the cardano-wallet service on the Pegasus backend service the correct total blocks was shown (42).
I will report this issue on IOHK's cardano-wallet repository.

The total number of blocks produced by YYG pool is now consistent on both pooltool web and mobile app.
